// Control de flujo y manejo de errores

// ejemplo 1
{
    var d = 3;
}

// ejemplo 2 condicionales
if (d) {

} else {

}

switch (key) {
    case value:
        
        break;

    default:
        break;
}

// ejemplo 3 bucles

for (let index = 0; index < array.length; index++) {
    const element = array[index];
    
}
//
while (condition) {
    
}
//
do {
    
} while (condition);
//
for (const iterator of object) {
    
}
//
for (const key in object) {
    if (Object.hasOwnProperty.call(object, key)) {
        const element = object[key];
        
    }
}

// ejemplo 4 funciones
function name(params) {
    
}

// ejemplo 5 errores
try {
    
} catch (error) {
    
}

